version: '3'

services:
  mysql:
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_create_table.sql:/docker-entrypoint-initdb.d/01_mysql_create_table.sql
      - ./insert_tables.sql:/docker-entrypoint-initdb.d/02_insert_tables.sql
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf

  python_app:
    build:
      context: .
    depends_on:
      - mysql
    volumes:
      - .:/app
