version: '3'
services:   
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'tearsheets'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'test'
    volumes: 
      - type: bind
        source: ./mysql_create_tables.sql
        target: /docker-entrypoint-initdb.d/mysql_create_tables.sql
    ports:
      - "3336:3306"
    networks:
      - tearsheets

  redis:
    image: redis:7.0.8-alpine
    environment:
      - REDIS_PASSWORD=test
    ports:
      - "6339:6379"
    networks:
      - tearsheets

  tearsheets:
    build: ./
    environment:
      LOG_LEVEL: "DEBUG"
      DB_HOST: 'db'
      DB_USER: 'test'
      DB_PASS: 'test'
      DB_PORT: 3336
      DB_DATB: 'tearsheets'
      DB_ENGN: 'mysql'
      RDS_HOST: 'redis'
      RDS_DATB: 0
      RDS_PORT: 6339
    volumes: 
      - type: bind
        source: ./main.py
        target: /usr/app/main.py
    ports:
      - "3778:3778"
    depends_on:
     - 'db'
     - 'redis'
    networks:
      - tearsheets

networks:
  tearsheets:
    driver: bridge
